<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="SqlServerDatabaseComparerTest.CompareAsync.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\Testing.Databases.SqlServer.Tests.Source\bin\$(Configuration)\netstandard2.1\Testing.Databases.SqlServer.Tests.Source_Create.sql" Link="Testing.Databases.SqlServer.Tests.Source_Create.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Testing.Databases.SqlServer.Tests.Target\bin\$(Configuration)\netstandard2.1\Testing.Databases.SqlServer.Tests.Target_Create.sql" Link="Testing.Databases.SqlServer.Tests.Target_Create.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SqlServerDatabaseComparerTest.CompareAsync.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Testing.Databases.SqlServer.SqlCmd\Testing.Databases.SqlServer.SqlCmd.csproj" />
    <ProjectReference Include="..\Testing.Databases.SqlServer.Tests.Source\Testing.Databases.SqlServer.Tests.Source.csproj" ReferenceOutputAssembly="False" />
    <ProjectReference Include="..\Testing.Databases.SqlServer.Tests.Target\Testing.Databases.SqlServer.Tests.Target.csproj" ReferenceOutputAssembly="False" />
  </ItemGroup>

  <Import Project="..\Testing.Databases.SqlServer.Shared.Tests\Testing.Databases.SqlServer.Shared.Tests.projitems" Label="Shared" />

</Project>
