<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\Testing.Databases.SqlServer.Tests.DacPac\bin\$(Configuration)\netstandard2.1\PosInformatique.Testing.Databases.SqlServer.Tests.DacPac.dacpac" Link="PosInformatique.Testing.Databases.SqlServer.Tests.DacPac.dacpac">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\src\Testing.Databases.SqlServer.Dac\Testing.Databases.SqlServer.Dac.csproj" />
    <ProjectReference Include="..\Testing.Databases.SqlServer.Tests.DacPac\Testing.Databases.SqlServer.Tests.DacPac.csproj" ReferenceOutputAssembly="False" />
  </ItemGroup>
  
  <Import Project="..\Testing.Databases.SqlServer.Shared.Tests\Testing.Databases.SqlServer.Shared.Tests.projitems" Label="Shared" />

</Project>
