name: Release

on:
  workflow_dispatch:
    inputs:
      VersionPrefix:
        type: string
        description: The version of the library
        required: true
        default: 1.0.0
      VersionSuffix:
        type: string
        description: The version suffix of the library (for example rc.1)

run-name: ${{ inputs.VersionPrefix }}-${{ inputs.VersionSuffix }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      
      - name: Build UnitTests.Databases.SqlServer
        run: dotnet pack 
          --property:Configuration=Release
          --property:VersionPrefix=${{ github.event.inputs.VersionPrefix }}
          --property:VersionSuffix=${{ github.event.inputs.VersionSuffix }}
          "src/UnitTests.Databases.SqlServer/UnitTests.Databases.SqlServer.csproj"

      - name: Build UnitTests.Databases.SqlServer.EntityFramework
        run: dotnet pack 
          --property:Configuration=Release
          --property:VersionPrefix=${{ github.event.inputs.VersionPrefix }}
          --property:VersionSuffix=${{ github.event.inputs.VersionSuffix }}
          "src/UnitTests.Databases.SqlServer.EntityFramework/UnitTests.Databases.SqlServer.EntityFramework.csproj"

      - name: Publish the package to nuget.org
        run: dotnet nuget push "src/**/bin/Release/*.nupkg" --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json
